#!/bin/zsh

[[ $(hostname) != *wsl* ]] && echo "" && exit 0

if git_status=$(cd $1 && git status 2>/dev/null ); then
    git_branch="$(echo $git_status| awk 'NR==1 {print $3}')"
    case $git_status in
        *Changes\ not\ staged* ) git_info="#[fg=red] ⭠ ${git_branch}" ;;
        *Changes\ to\ be\ committed* )  git_info="#[fg=cyan] ⭠ ${git_branch}" ;;
        * )  git_info="#[fg=green] ⭠ ${git_branch}" ;;
    esac
else
    git_info=""
fi

directory="#[fg=cyan]$1"

echo "$directory$git_info"
